# Generated by Django 3.1.6 on 2021-02-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='desc',
            new_name='dsc',
        ),
    ]
